development:
  url: {{envOr "TEST_DATABASE_URL" "postgres://postgres:postgres@localhost:5439/yume_development?sslmode=disable"}}
  pool: 5

test:
  url: {{envOr "TEST_DATABASE_URL" "postgres://postgres:postgres@localhost:5439/yume_test?sslmode=disable"}}

# production:
#   url: {{envOr "DATABASE_URL" ""}}
#   pool: 5
