version: "3.7"
volumes:
  yume-postgres:
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5439:5432"
    volumes:
      - yume-postgres:/postgresql
