version: "3.7"
volumes:
  yume-postgres:
  yume-redis:
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5439:5432"
    volumes:
      - yume-postgres:/postgresql
  redis:
    image: redis:6
    command: "redis-server --appendonly yes"
    ports:
      - "6380:6379"
    volumes:
      - yume-redis:/data
